compile with g++

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -11,7 +11,8 @@ ccoption=''
 ccflags=''
 asmflags=''
 verbose=no
-
+cxx=''
+cxxflags=''
 
 # Parse command-line arguments
 
@@ -33,8 +34,10 @@ while : ; do
         ccflags=$ac_optarg;;
     -asm-opts*|--asm-opts*)
         asmflags=$ac_optarg;;
-    -cc*|--cc*)
-        ccoption=$ac_optarg;;
+    -cxx-opts*|--cxx-opts*)
+        cxxflags=$ac_optarg;;
+    -cxx*|--cxx*)
+        cxxflags=$ac_optarg;;
     -verbose|--verbose)
         verbose="yes";;
     -m*|--m*|-abi*|--abi*)
@@ -42,6 +45,7 @@ while : ; do
     -h|--help|-\?|help|\?)
         echo "./configure [options]"
         echo "  --cc=<ccomp>                   set the c-compiler (for example 'clang')"
+        echo "  --cxx=<ccomp>                  set the c++-compiler (for example 'clang++')"
         echo "  --cc-opts=<options>            set extra c-compiler options (for example '-m32')"
         echo "  --asm-opts=<options>           set extra assembler options (for example '-m32')"
         echo "  --abi=<abi>                    set ABI (for example: 'x86' or 'amd64')"
@@ -82,6 +86,14 @@ else
 fi
 
 ccname="$(basename $cc)"
+
+if test -z "$cxx"; then 
+  case "$ccname" in
+    gcc) cxx=${cc/%gcc/g++};;
+    clang) cxx=${cc/%clang/clang++};;
+    *) cxx="$cc";;
+  esac
+fi
 
 # Determine the system type
 if test "$target_type" = "unknown"; then	
@@ -201,7 +213,8 @@ case "$ccname" in
     asm=".s";;
   cl)
     cclinkflags="-nologo"
-    ccflags="-nologo -W3 -Za $ccflags"
+    ccflags="-Tc -nologo -W3 -Za $ccflags"
+    cxxflags="-Tp -nologo -W3 -Za $ccflags"
     ccflagopt="-O2 -GS- -GT"  # fiber-safe optimize
     ccflagdebug="-Zi"
     ar="lib"
@@ -216,9 +229,12 @@ case "$ccname" in
   gcc*)   
     ccflags="-Wall $ccflags"
     ccflag99="-std=c99 -pedantic"
+    cxxflags="-std=c++11 $ccflags"
     asmflags="-Wall $asmflags";;
   clang*)
     ccflags="-Wall $ccflags"
+    ccflag99="-std=c99"
+    cxxflags="-std=c++11 $ccflags"
     asmflags="-Wall $asmflags";;
   *)
     echo "warning: unknown c-compiler '$ccname' -- command options might be wrong";;        
@@ -230,12 +246,12 @@ esac
 ccomp=$cc
 cclibs=""
 ccout="$linkflagout"
-export cc ccflags ccout cclibs verbose exe
+export cc ccflags ccout cclibs verbose exe cxx cxxflags
 
 # Check C c-compiler
 sh ./runtest c99.c
 case $? in
-  0) echo "The C compiler is C99-compliant.";;
+  0) echo "The C compiler is C99 compliant.";;
   1) echo "The C compiler '$cc' is not C99 compliant."
      echo "A C99 compliant compiler might be required to build (due to line-comments etc).";;
   *) echo "Unable to compile the test program."
@@ -244,6 +260,17 @@ case $? in
      exit 2;;
 esac
 
+# Check C c-compiler
+sh ./runtest++ c++11.cpp
+case $? in
+  0) echo "The C++ compiler is C++11 compliant.";;
+  1) echo "The C++ compiler '$cxx' is not C++11 compliant."
+     echo "A C++ 11 compliant compiler might be required to build.";;
+  *) echo "Unable to compile the test program."
+     echo "Make sure the C++ compiler '$cxx' is properly installed."
+     env verbose="yes" sh ./runtest++ c++11.cpp
+     exit 2;;
+esac
 
 # Set up cenv.h
 echo "// Generated by 'configure': C environment constants" > cenv.h
@@ -351,6 +378,11 @@ echo "LINK=$link" >> makefile.inc
 echo "LINKFLAGS=$linkflags" >> makefile.inc
 echo "LINKFLAGOUT=$linkflagout" >> makefile.inc
 
+echo "CXX=$cxx" >> makefile.inc
+echo "CXXFLAGS=$cxxflags" >> makefile.inc
+echo "CXXFLAGSOPT=$cxxflags $ccflagopt" >> makefile.inc
+echo "CXXFLAGSDEBUG=$cxxflags $ccflagdebug" >> makefile.inc
+
 echo >> makefile.inc
 
 echo "EXE=$exe" >> makefile.inc
@@ -384,7 +416,8 @@ echo "--- Configuration summary ---"
 echo "System:"
 echo "  target      : $target_abi-$target_os"
 echo "Build:"
-echo "  c compiler  : $cc $ccflags"
+echo "  c compiler  : $cc $ccflag99 $ccflags"
+echo "  c++ compiler: $cxx $cxxflags"
 echo "  assembler   : $cc $asmflags"
 echo "  linker      : $link $cclinkflags"
 echo
